### ISSUE TITLE
不需要那么复杂

### ISSUE THREAD

**Issue by chdo002** [good-good-study/scroll_page_view#3]
[PageView.builder就是无限的](https://stackoverflow.com/questions/49161719/is-there-a-way-to-have-an-infinite-loop-using-pageview-in-flutter)

**Comment by good-good-study** [comment]
你要设置无限数据长度啊？

**Comment by chdo002** [comment]
itemCount 不设置的时候就是无限个，然后对实际数据源取余就行了
唯一需要处理的是初始位置设置个比较大的就行

**Comment by good-good-study** [comment]
这么干很浪费😂
